---
"on":
  schedule:
    - cron: '0 */6 * * *'
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup env
        run: |
          {
            echo "upstream-hosts=${{ runner.temp }}/upstream-hosts";
            echo "processed-hosts=${{ runner.temp }}/processed-hosts";
            echo "final-hosts=steven-black-unified-unbound";
          } >> "$GITHUB_ENV"

      - name: Install Hosts-BL
        uses: jaxxstorm/action-install-gh-release@v2.1.0
        with:
          repo: ScriptTiger/Hosts-BL
          tag: 13APR2023
          cache: enable
          chmod: 0755

      - name: Download upstream hosts
        run: |
          curl -qsLo ${{ env.upstream-hosts }} \
            "https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts"

      - name: Convert to unbound format
        run: |
          hosts-bl \
            -f unbound \
            -i ${{ env.upstream-hosts }} \
            -o ${{ env.processed-hosts }}

      - name: Remove allowlisted entries
        run: |
          grep \
            --invert-match \
            --file=allowlist \
            ${{ env.processed-hosts }} > ${{ env.final-hosts }}

      - name: Create job summary
        run: |
          # exit early if no diff
          git diff --quiet --exit-code ${{ env.final-hosts }} && exit 0
          {
            echo "# ${{ env.final-hosts }} Diff";
            echo $'```';
            git diff ${{ env.final-hosts }};
            echo $'```';
          } >> "$GITHUB_STEP_SUMMARY"

      - name: Commit & Push changes
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions-js/push@v1.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
