---
"on":
  schedule:
    - cron: '0 */6 * * *'
  push:
    branches:
      - main

env:
  OUT_FILE: steven-black-unified-unbound
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version: stable
          check-latest: true

      - name: Generate file
        run: |
          go install github.com/ScriptTiger/Hosts-BL@latest
          curl -qsLO \
            "https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts"
          /home/runner/go/bin/Hosts-BL \
            -f unbound \
            -i hosts \
            -o - \
          | grep -v 'klclick.\?\.com' >> ${{ env.OUT_FILE }}

          rm -f hosts

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
